zahinekbal/codeWith-hacktoberfest

paritoshkray_MergeSort.cpp
added Merge Sort algorithm in C++
=> added merge sort in C++

Optimal Binary Search Tree using DP.cpp
added c++ code for Optimal Binary Search Tree Using Dynamic Programming with PR #12 
please review and do merge :-)
=> add: Optimal Binary Search Tree Using Dynamic Programming

BinarySearchTree.c
Added Binary Search Tree in C language
BinarySearch-Tree #8
Operations : Deletion , Insertion and Traversals (Inorder , preorder and postorder).
BinarySearchTree.c
=> Added Binary Search Tree in C 

PyramidPatternProblem/C/pyramidpattern1.c, PyramidPatternProblem/JAVA/PyramidPattern1.java, PyramidPatternProblem/PYTHON/pyramidpattern1.py, PyramidPatternProblem/PyramidPatternProblem1.cpp
this is in reference to issue #30 .I have added rectangular pyramid pattern in all the four languages .Will add more patterns in few days .Kindly see if it can be merged as I have tried creating the same folder structure as mentioned in issue.
=> pyramid rectangular pattern added in all languages

RotateTheArray/C/RotateArrayByN.c
This is a C code which will rotate the array elements by n no.of steps #5
=> RotateArrayCprog

stair.cpp
Hi @zahinekbal i have implemented a dp solution to this problem. Please accept my PR.
=> DP solution staircase problem

docker/flask/Dockerfile, docker/flask/app.py, docker/flask/docker-compose.yml, docker/flask/requirements.txt
aplicacion web en python con archivos de configuracion docker para crear una imagen
=> aportación

RotateTheArray/Java/RotateArrayGCD.java
- Optimization for rotating elements is done with GCD logic.
- If size of array is smaller than the rotation size that is also handled.
- Comments in code for better understanding for readers.
=> Rotate the Array using GCD approach

BinarySearchTree.py
=> Added binary search tree in python

BankersAlgorithm.c
Added Bankers Algorithm implemented in C. 😄
=> Added Bankers algorithm

STL/CPP/valid_parentheses.cpp
Solution for Balanced Brackets or Valid Parentheses using C++ STL stack
Links to Question
HackerRank: 	https://www.hackerrank.com/challenges/balanced-brackets/problem/
LeetCode: 	https://leetcode.com/problems/valid-parentheses/
=> Valid Parentheses C++ STL stack

C++ Stl problem/Question.md, C++ Stl problem/solution.cpp
Added a STL problem in the folder C++ Stl Problem which contains two files :
Question.md (contain question)
solution.cpp(contains the solution )
=> Added a Problem of c++ STL problem

Vector(STL)/Question.md, Vector(STL)/VectorSort.cpp
I have added a problem from hackerrank which tells to sort a vector using STL.
=> Added Vector STL

paritosh_RadixSort.cpp
added radix sort implementation in C++
=> added radix sort in C++

Rotten oranges c++
Using dynamic programming approach with time complexity o(R*C)
=> Rotten oranges c++

STL/CPP/minimum_cost_of_ropes.cpp
added priority_queue CPP STL implementation
=> added STL/CPP/minimum_cost_of_ropes.cpp

Codeforces/CPP/665 div_2/A.cpp, Codeforces/CPP/665 div_2/problem_links.md, Codeforces/CPP/666 div_2/A.cpp, Codeforces/CPP/666 div_2/B.cpp, Codeforces/CPP/666 div_2/problem_links.md, Codeforces/CPP/671 div_2/A_Digit_Game.cpp, Codeforces/CPP/671 div_2/B_Stairs.cpp, Codeforces/CPP/671 div_2/C_Killjoy.cpp, Codeforces/CPP/671 div_2/D1_Sage_s_Birthday_easy_version_.cpp, Codeforces/CPP/671 div_2/D2_Sage_s_Birthday_hard_version_.cpp, Codeforces/CPP/671 div_2/problem_links.md, Codeforces/CPP/672 div_2/A_Cubes_Sorting.cpp, Codeforces/CPP/672 div_2/B_Rock_and_Lever.cpp, Codeforces/CPP/672 div_2/C1_Pok_mon_Army_easy_version_.cpp, Codeforces/CPP/672 div_2/problem_links.md, Codeforces/CPP/grankforce/A_Circle_Coloring.cpp, Codeforces/CPP/grankforce/problem_links.md
added Codeforces solutions corrected format. it contains solutions for Div 2 665,666,671,672 and graknforce contest
link to those problems are in problem_link.md
Thank you :)
=> added codeforces solutions corrected format

DFS/CPP/DFS.cpp
added DFS traversal for an undirected graph (recursive implementation)
=> added DFS/CPP/DFS.cpp

BFS/CPP/BFS.cpp
**Problem link**: https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1
**problem type**: graph traversal
**statement** : Given a directed graph. The task is to do Breadth First Search of this graph.
issue no #58
=> Create BFS/CPP/BFS.cpp with changed file name and file format corrected

codeforces/CPP/656/Three-Pairwise-Maximums.cpp, codeforces/CPP/656/ThreePairwiseMaximums.cpp
=> ThreePairWiseMaximums

SortingAlogrithm/python/bubble sort.py, SortingAlogrithm/python/insertion sort.py, SortingAlogrithm/python/optimiesd bubble sort.py
all algorithms are added in given format.
=> added sorting algorithms in python language

C++ Stl problem/usingcomparators_stl.cpp
Demonstrating the use of comparators issue #3
=> using comparators with STL in c++

FrontEndWebsite/Animated (Landing)Home Page/README.md
As you commented on the last pull req. , Hosted the "__Animated Homepage Website__" & Gave its link in Readme file of the folder.
😃
=> Specified Website Link in the Readme File 

STL-unordered_map/Problem.md, STL-unordered_map/freq_count.cpp
Shows a useful application of unordered_maps.
=> added about unordered_map in STL

Bellman-Ford/Bellman Ford.cpp
Bellman ford algorithm implementation to find single source shortest path in a graph.
=> bellman-ford

SubsetSum/CPP/SubsetSum.cpp
Added the code for the famous dynamic programming problem Subset Sum.
=> Add Subset Sum Problem Algorithm

DutchFlagProblem/CPP/DutchFlagProblem.cpp
Added code for the famous Dutch Flag Problem which sorts an array containing 0, 1, 2 only, in linear time.
=> Add Dutch Flag Problem Algorithm

SortingAlgorithms/C/Bubble_Sort.c, SortingAlgorithms/C/Insertion_Sort.c, SortingAlgorithms/C/Merge_Sort.c, SortingAlgorithms/C/Selection_Sort.c
This is the contribution to the Issue #7
=> #7  Added Few of the Sorting Algorithms in C

InvertionCount/CPP/InvertionCount.cpp
Used Merge Sort to solve the problem in O(n log n) time complexity.
=> Added InvertionCount in C++

Dynamic Programming/0:1 Knapsack.cpp, Dynamic Programming/Equal_sum_partition.cpp, Dynamic Programming/Subset Sum Problem.cpp
=> Added Dynamic Programming algorithms

C++ Stl problem/solution 2.cpp
=> Create solution 2.cpp

C++ Stl problem/Question 2.md
=> Create Question 2.md

Hangman game.py, Programmer's day special wish.py
=> Added all the files 

python/Checking-Prime-Number.py, python/Factorial-of-a-number-in-Python.py
Uploaded two Python programs to the folder Python:
1) To find the Factorial value of a number
2) To check whether the number is a Prime number or not.
=> Added two Python programs into the folder Python

Imakshat47_binary2DecimalBasic.cpp, Imakshat47_binary2DecimalUsingInBuildFun.cpp, Imakshat47_binary2DecimalUsingString.cpp, Imakshat47_binary2Octal.cpp, Imakshat47_decimal2OctalBasic.cpp, Imakshat47_decimal2OctalFormula.cpp, Imakshat47_decimal2binaryBasicArray.cpp, Imakshat47_decimal2binaryBasicVoid.cpp, Imakshat47_decimal2binaryUsingBitwise.cpp, Imakshat47_octal2binary.cpp
Added C++ Maths Number Conversion Programs
=> Updates: C++ Maths Number Conversion Programs

Mad libs game.py
=> Files added

Codeforces/CPP/Codeforces_667_Div3/A.cpp, Codeforces/CPP/Codeforces_667_Div3/B.cpp, Recursion/Flood_fill_algorithm.cpp
Hello!
I added the _Flood-fill algorithm_ implemented in C++ in a new folder named _Recursion_. The flood fill algorithm works in a way similar to the bucket tool in MS Paint. This Is also a really famous interview problem. I hope this is a decent addition to your repository.
Thanks!
=> Added the Flood-fill algorithm in recursion folder

RotateTheArray/Swift/RotateTheArray.swift
Added a swift array extension to rotate the array.
=> Swift - add rotate the array 

Interviewbit/StackQueue/balanced_parantheses.cpp, Interviewbit/StackQueue/first_non_repeating_character.cpp, Interviewbit/StackQueue/redundant_braces.cpp
Added codes for Stack and Queue questions of Interviewbit with Question link and proper comments.
Added codes in cpp for:
1. balanced parentheses.cpp
2. first_non_repeating_character.cpp
3. redundant_braces.cpp
=> Added Stack and Queue questions for Interviewbit problems with ques link and comments.

Codeforces/CPP/666 div_2/C.cpp, Codeforces/CPP/666 div_2/problem_links.md
Logical Question with Easy Solution with explanation in comments.
Updated the folder with subsequent question.
=> Codeforces round #666 C solution added with explanation
